### PR TITLE
Update copyright to 2015

### PR DESCRIPTION
**Pull request by leggetter**
This one took me forever. Phew!

### CODE REVIEW

**Comment by andy-berry-dev** [comment]
Great change!! Thanks @leggetter  :smile:

**Comment by janhancic** [comment]
Could we just do `copyright Caplin 2005 - present`? I saw today FB does that :)

**Comment by andy-berry-dev** [comment]
@janhancic Sounds good. Are you also volunteering to do the pull request? :-)

**Comment by janhancic** [comment]
:) yeah why not :)

**Comment by andy-berry-dev** [comment]
:+1:

**Pull request merged**
