### PR TITLE
Adding sprint blog post and image

### PR DESCRIPTION
**Pull request by sospirited**

### CODE REVIEW

**Comment by andy-berry-dev** [comment]
Looks good (apart from the _config.yml entry which you now know about), @leggetter might wan't a quick look before I push the button....?

**Comment by leggetter** [comment]
I'd suggest a better title. Something that provides an overview of what we were up to - if possible.

No release this sprint? May be worth a note as to why.

Looks like there's a `DunDDD` link in there somewhere which doesn't actually link to the event. Which is http://dun.dddscotland.com/

'which was quite well received' - Just 'quite'? ;) I'd just say 'well'.

Config looks and works fine.

**Comment by sospirited** [comment]
Thanks @leggetter 
1. I've updated the title to:
'BladeRunnerJS Sprint Demo #3 - Bug fixes and Bundler Plugin architecture'
I've run this title naming convention past @andyberry88 and we think it's a decent title naming convention we can go with for future sprints.
1. Updated 'quite well' --> 'well' ;-)
2. Updated reference to 'previous v0.2 release' to refer to v0.3 release instead and updated the link
3. Added DunDDD hyperlink

Should be good to push live soon as we have a downloadable release for people to download

**Comment by leggetter** [comment]
:+1:

**Pull request merged**
