### PR TITLE
Updates to the blades page

### PR DESCRIPTION
**Pull request by fauna5**

### CODE REVIEW

**Comment by leggetter** [comment]
@fauna5 Could this pull request please be made against the develop branch? That branch has the most up to date information.

**Comment by fauna5** [comment]
Will do later. Can you update the readme to talk about the status of branches so that anyone else new doesn't start from the wrong base.

**Comment by leggetter** [comment]
I've updated the default branch to be `develop` so it will be used by default and any pull requests will go against it too.

**Comment by andy-berry-dev** [comment]
> I've updated the default branch to be develop 

One thing to note with this: This means anyone syncing by default will get the 'develop' branch. That's the reason why the `brjs` repo still has master as the default but pull requests should still go into develop.  Also any GitHub code searches will only search the default branch.

**Comment by dchambers** [comment]
If you're syncing the code then you almost certainly do want to develop, so that's probably the right thing no?

**Comment by andy-berry-dev** [comment]
It depends whether you expect to be immediately syncing stable code or expect to have to find what the stable code branch is. Personally I'd expect to sync a stable code branch (master) and have to checkout develop if I'm a committer and want to make some fixes.

**Comment by leggetter** [comment]
We're in the middle of a lot of changes to the docs on the site so IMO right now it makes sense for `develop` to be the default. In @fauna5's case it would have meant the changes were definitely usable. As it stands they may not be relevant as those paragraphs may have completely changed.

**Comment by andy-berry-dev** [comment]
> We're in the middle of a lot of changes to the docs on the site so IMO right now it makes sense for develop to be the default.

Happy with that, just thought I'd mention the side effects it has. The above reasons are why BRJS still uses master as the default branch but commits and PRs tend to go into develop.

**Pull request closed without merging**
